/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>
#include <opencv2/videoio.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgcodecs.hpp>

using namespace cv;
using namespace std;
/* Header for class com_example_matjeusz_opencv_OpenCVNativClass */

#ifndef _Included_com_example_matjeusz_opencv_OpenCVNativClass
#define _Included_com_example_matjeusz_opencv_OpenCVNativClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_matjeusz_opencv_OpenCVNativClass
 * Method:    convertGray
 * Signature: (JJ)I
 */

int toGray(Mat img, Mat& gray);

JNIEXPORT jint JNICALL Java_com_example_matjeusz_opencv_MainActivity_add
        (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_example_matjeusz_opencv_MainActivity_add1
        (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_example_matjeusz_opencv_MainActivity_add2
        (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_example_matjeusz_opencv_MainActivity_add3
        (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_example_matjeusz_opencv_OpenCVNativClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
